In [1]:
# Library imports
from math import exp, log
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [2]:
df = pd.read_csv('data.csv')
num_classes = 3
num_b = len(df.columns)
b = np.zeros((num_classes, num_b))
num_obs = df.shape[0]

In [3]:
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
def probability(c, i):
    a = df.loc[i].to_numpy()
    u = b[c][0] + np.dot(b[c][1:], np.transpose(a[:len(a) - 1]))
    return 1 / (1 + exp(-u))

def log_loss():
    # return a list of losses or maybe add a column to the df_beta dataframe
    loss = np.zeros(num_classes)
    # for each class -> for each obs -> add probability to the corresponding class in j
    for i in range(num_classes):
        for j in range(num_obs):
            p = probability(i, j)
            yes = (df.loc[j, 'class'] == i) * 1
            # print(i, yes)
            try:
                loss[i] += yes * log(p) + (1 - yes) * log(1 - p)
            except:
                print('diverges')
                return None
    loss = np.multiply(loss, -1 / num_obs)
    return loss

In [6]:
print(log_loss())

[0.69314718 0.69314718 0.69314718]


In [4]:
def iterate(epochs, learning_rate):
    for i in range(epochs):
        for j in range(num_classes):
            db = np.zeros(num_b)
            for k in range(num_obs):
                yes = (df.loc[k, 'class'] == j) * 1
                temp = probability(j, k) * (2 * yes - 1)
                db[0] += temp
                for l in range(1, num_b):
                    db[l] += df.iloc[k, l - 1] * temp
            db = np.multiply(db, -1 / num_obs)
            b[j] = np.subtract(b[j], learning_rate * db)

In [7]:
iterate(100, 0.001)
print(b)
print(log_loss())

[[ 0.03827101  1.31955571 -0.16239309 -0.13934931]
 [ 0.03894297 -0.14949413  1.00561499 -0.13935374]
 [ 0.03755659 -0.14947919 -0.1623814   1.76271873]]
diverges
None
